### ISSUE TITLE
Visual design tweaks

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#178]
A few quick items to adjust for the current visual design:

- [x] Remove the green color change upon making a parallelogram

- [x] Remove the bolding of the lines when all sides are equal.

- [x] Corner guide changes
  - [x] Revert right angle indicator from only showing when all are right angles to individual right angles (when any angle is a right angle, the corner guide converts to the square symbol).
  - [x] Only show when the Corner Guides are enabled.
  - [x] Keep the dashed lines from the corner guides in place.
  - [x] Draw the right angle symbol all the way to the dash lines as we do with the corner guide "fans".

- [x] Draw the play area boundary over the grid. Don't let the grid draw past the rounding of the play area boundary (if it makes more sense to decrease the roundedness of the play area boundary, then let's do that enough to cover the grid).
![image](https://user-images.githubusercontent.com/47331395/180504744-c9fcfe0c-ec2a-4941-8f59-4b2aa5ced56d.png)

- [x] Change "Symmetry Grid" to an icon. We can use the same icon from Vector addition for a first pass. Change title of icon/checkbox to "Grid"
![image](https://user-images.githubusercontent.com/47331395/182395756-0a42557a-7adb-400a-b3c2-275812adcbd9.png)

- [x] Adjust Checkbox labels to size 18 text (if not already) and resize the checkboxes to match the vertical height of the text (need to be a little smaller)

- [x] Change (darken) the background color of the **Play Area** to increase contrast: RGB 67 67 255 (#4D4DFF). Leave control area the same color it is currently.
![Image](https://user-images.githubusercontent.com/47331395/182189451-4b1e85e9-9531-4956-a530-dac22f58928c.png)

- [x] Change the color of the grid to white for better contrast: RGB 255 255 255 (#FFFFFF)

- [x] Change (lighten) color of Diagonal Guides for better contrast with new background and differentiation from grid: RGB 200 200 200 (#C8C8C8)

- [x] By default, re-enable the brief lighter yellow flash of the shape when transitioning between any shape that was present under the "Shape Identification Feedback" checkbox in the pref menu. Let's leave off the "tick" sound for now however. 
![image](https://user-images.githubusercontent.com/47331395/182413914-9fef3167-476a-424a-9685-068c18d00fbb.png)

**Comment by BLFiedler** [comment]
Bumping this up for implementation when there's time for it.

**Comment by jessegreenberg** [comment]
For the right angle guides, here is an example of the layout drawn with Zoom tools during design meeting today (ignore the red color)
![image](https://user-images.githubusercontent.com/6396244/182422453-c05accf7-04fc-412c-ac99-8dc93016009e.png)

**Comment by BLFiedler** [comment]
I was trying to think of a way to help with the centering of the vertices on the grid without obscuring the label - something simple like this could work? Do we think it'd be best to have them on all the time or only when the grid is on?

![Image](https://user-images.githubusercontent.com/47331395/183085506-a00b9537-38c3-47dd-b4c2-26ac393130db.png)

- [ ] Add small hatch marks that are statically oriented at 0, 90, 180, and 270 degrees for each vertex (they don't rotate like the diagonal or corner guides).

**Comment by jessegreenberg** [comment]
I think I am caught up with what is listed here.

Some notes from the changes:
 - I found a bug with the grid, it wasn't exactly aligned with the model grid/bounds. Fixed with these changes.
 - The checkbox label text size was changed to 18. This reduced the amount of space for the play area.
 - "Change title of icon/checkbox to "Grid" "- I assumed this meant change the Voicing label to "Grid" now that the title was removed.
 - Over Slack I asked @BLFiedler 
   - > Was the grid supposed to be on top or underneath the quadrilateral?
   - > For now I think on top works well for lining things up.
 - The crosshairs of the corner guide are thin enough that they are hidden behind the grid when it aligns perfectly.

@BLFiedler over to you to review progress and consider next steps.

**Comment by BLFiedler** [comment]
Hm. I am not sure the background color achieved what I wanted when everything was put together. It's a bit hard to look at. Possibly a future color contrast should have the dark/light switch between the play area and control area.

Let's revert a bit and just tweak the old color scheme for now to get to the WCAG standards for contrast with both white and black (for large text and non-text markings)

- [ ] Background (play area and control area): #8585FF (RGB 133 133 255) - slightly darker blue
- [ ] Corner Guide Dashes and Diagonal Guides: #000000 (RGB 0 0 0) - black
- [ ] Grid lines: #FFFFFF (RGB 255 255 255)

Wrt layering, the diagonal guides look like they've been moved up. Let's
- [ ] Draw the diagonal guides behind the vertices and corner guides.

That should hopefully do a bit better for future feedback.

**Comment by jessegreenberg** [comment]
Colors changed as requested. I reverted the change to the diagonal guide z-order, it is behind the quadrilateral again. Back to @BLFiedler.

**Comment by BLFiedler** [comment]
Discussed in meeting to increase legibility of corner labels. Let's,

- [ ] Draw grid in the back.
- [ ] Have vertex hatch marks only appear when Grid is on.
- [ ] Change color of vertex hatch marks to #FFFFFF (RGB 255 255 255)

**Comment by jessegreenberg** [comment]
Changes requested during meeting made above, back to @BLFiedler.
