### ISSUE TITLE
Quadrilateral Checklist

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#2]
# Quadrilateral checklist

## Design
- [x] **Sim folder and design doc created** (Date: 2021)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design docs in the sim folder
      - [Voicing Design Doc](https://docs.google.com/document/d/1jXayebAWnnNzsT3l6o72YPw4-YtiQaHQNuAi64eiguc/edit#heading=h.8xiwvsotqg0p)(Date started: 10/12/2021; Date completed: 09/03/2023 with final tweak to Overview)
- (N/A) **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
   - (N/A) *If a Port:* Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [x] **Learning goals and standards identified** (Date: Spring 2022)
- [x] **Design concept complete**  (Date: Sep 2022)
- (N/A) **Wireframes complete** - Visuals took a back seat here, but there was a lot of wire-framing of the descriptions.
- [x] **Mockups complete** (Date: //) *not applicable to this sim design
- [x] Visual display checked for colorblind and greyscale (latest: 3/21/2023)
- (N/A) **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: Sep 2021, Feb 2022, June 2022 (SOAR @ SLU),  Aug 2022, Dec 2022 (1 remote Voicing interview))
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: April 2023)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] #419
  - [x] Teacher Guide created, uploaded, and added to sim design folder (see https://github.com/phetsims/quadrilateral/issues/29)
  - [x] Sim Primer
  - [x] Sound Features Video
  - LoL: (BF: I don't believe this is relevant for us here. If someone wants to put it up on the platform, we can revisit).
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - (N/A) *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [ ] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [ ] Hold postmortem if applicable (Date: //)

## Implementation
- [x] **Repository created** (Date: 8/18/21)
  - [x] Simulation added to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 8/18/21)
- [x] **Sim is "feature complete"** (Date: 3/27/2023)
    - [x] Voicing Feature Implementation (Date started: 11/12/2021; Date completed: 24/03/2023 with closing of #267)
- [x] **QA team "first look"** (Date: 1/12/23)
- [x] Interviews may happen around here (see above)
- [x] **Code review checklist completed"** (Date: 3/22/23)
- [ ] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: 3/21/2023)
- [x] **Sim dev test completed** (Date: 3/30/23)
- [x] **Sim RC tests completed** (Date: 5/15/23)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks - see [conventions](https://github.com/phetsims/joist/blob/master/js/CreditsNode.js))
  - [x] Add CT tests for public query parameters
- [x] **Published** (Date: //)

## QA
- (N/A) *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 1/8/23)
- [x] **Dev testing completed** (Date: 1/23/23)
- [x] **First RC published** (Date: 4/3/23)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 5/15/23)

**Comment by jessegreenberg** [comment]
This simulation will be developed in collaboration with a few teams outside of the PhET project. There are also ambitions of working through initial design of this sim without graphical mockups. Unclear if it the development cycle illustrated in this checklist will apply to this sim. But might still be helpful to identify dates for various parts of development.

**Comment by terracoda** [comment]
Should we add the features that are planned for this simulation?
- Sonification
- Voicing (and eventually Interactive Description)
- Tangible UI
- Haptics

I added Voicing.

**Comment by BLFiedler** [comment]
@jessegreenberg , can you update any relevant approx dates or information in the above checklist as it relates to dev work?

**Comment by jessegreenberg** [comment]
Yep, I updated dates. One of the items hasn't been done: "Add CT tests for public query parameters". Ill do that now.

**Comment by terracoda** [comment]
The dates I put in go day-month-year. What is the preferred format?

**Comment by brettfiedler** [comment]
Thanks Quad. See ya.
