### ISSUE TITLE
Teacher Resources Checklist

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#29]
- [ ] **Sample Learning Goals for Sim Page**
  - [ ] Sim learning goals and standards alignment drafted in Design Doc
  - [ ] Added to sim page

- [ ] **Teacher Tips Doc**
  - [ ] Screenshot(s)
  - [ ] Verify Sound Design Doc is complete and linkable (if applicable)
  - [ ] Editable files and final PDF Uploaded to Sim folder in Google Drive
  - [ ] Published to Sim Page

- [ ] **Teacher Primer Video**
  - [ ] Script
  - [ ] Project files uploaded to Google Drive
  - [ ] Final review with team members
  - [ ] Captions
  - [ ] Uploaded to Vimeo
  - [ ] Published to Teacher Resources in Sim Page

- [ ] **Sound Features Video**
  - [ ] Script
  - [ ] Project files uploaded to Google Drive
  - [ ] Final review with team members
  - [ ] Captions
  - [ ] Uploaded to Vimeo (YouTube?)
  - [ ] Published to Teacher Resources in Sim Page

**Comment by BLFiedler** [comment]
For Teacher Tips and/or Model.md
- Shape Hierarchy figure/notes
- Model restrictions:
  - No crossed shapes

**Comment by terracoda** [comment]
@BLFiedler, let me know if you want me to take on any of the above tasks.

**Comment by terracoda** [comment]
For example, I can start a Teacher Tips doc from a Template. I found a template on the PhET files drive.

**Comment by BLFiedler** [comment]
Updated Primer Script: https://docs.google.com/document/d/1dkE_fISI2ebWlM9oR8dJMQCmzFogubtf/edit#

and Sound Feature script: https://docs.google.com/document/d/1AJkVbBIBa2XXxr182sj2yQ0lKeLA4DWlS6Ipo7P2c5o/edit

and Teacher Tips: https://www.icloud.com/pages/058QIDYfWb9HYLWhTvl7sMsOQ#quadrilateral-guide

NOTE: Google Drive migration is happening this weekend - so I'll have to update these links...

**Comment by BLFiedler** [comment]
Primer: https://youtu.be/EZ9JX1hE2Ic

**Comment by BLFiedler** [comment]
Sound Features: https://youtu.be/9-XwrVnNq5M

**Comment by terracoda** [comment]
@BLFiedler, I uploaded corrected teacher guide pages and pdf.
