### ISSUE TITLE
Interactive Description Design Checklist

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#74]
This issue helps tracks the big picture progress of the description design, description implementation, and implementation of alternative input. Sound and adaptive features are incorporated only at a high-level here, though could be added as we move forward and learn more.
 
# Inclusive Features 
- [ ] Alternative Input -  (Started: Feb 22, 2022) (Completed: )
- [ ] Interactive Description - (Started: Feb 22, 2022) (Completed: )
  - [ ] Mobile A11y included - (Started: ??) (Completed: )
- [ ] Sonification - (Prior to ID, see sound design doc)
- [ ] Voicing (Prior to ID, see voicing design doc)

# Design Tasks
- [x] Multimodal Features folder created in PhET Sim Design folder. Sub-folders (Interactive Desciption, Sound and Sonification, Voicing) created as needed. Description design doc created in Interactive Description sub-folder (Date: Feb 22, 2022)
- [x] Link to [{Quadrilateral: Interactive Description](https://docs.google.com/document/d/1oikq9CFhZ6ajEIkLLNcXDXCXDp9q2aThqcD69THMTqI/edit#) 

# Interactive Description

<details>
<summary>Interactive Description</summary>

## State Descriptions for PDOM 
**Checked items have names & structures identified & determined**
- [x] All interactive objects and their interaction types (e.g., sliders, buttons, etc.)
- [x] Corners and Sides are custom movable objects, trying one-step grab/drag interaction, like RaP Both Hands

## [State Descriptions](https://docs.google.com/document/d/1oikq9CFhZ6ajEIkLLNcXDXCXDp9q2aThqcD69THMTqI/edit#heading=h.v2c1rmmsi17s)
**Checked items drafted & ready for implementation**
### Static State Descriptions
- [x] Heading Outline (Sign Posts) & Navigation Order (Interaction Points) 
- [x] Static screen summary
- [x] Initial sim-specific interaction hint
- [x] Headings for objects/groups in Play Area
- [x] Names & interaction types for interactive objects
- [x] Help text for interactive objects 

### [Dynamic State Descriptions](https://docs.google.com/document/d/1oikq9CFhZ6ajEIkLLNcXDXCXDp9q2aThqcD69THMTqI/edit#heading=h.cickaapr2neb)
**Checked items completed in design document**
- [ ] PDOM section of Design Doc contains 1 clear example of each dynamic description
- [ ] More examples and possible edge cases have been explored for:
    - [ ] Dynamic screen summary (i.e., brief state-of-the-sim)
    - [ ] Dynamic states for identified dynamic objects (can add list to this issue)
- [ ] Dynamic parameters (scales and approximate ranges) for dynamic objects ready
    - [ ] Special case parameters or phrases for dynamic state descriptions identified (can add list)

## [Responsive Descriptions](https://docs.google.com/document/d/1oikq9CFhZ6ajEIkLLNcXDXCXDp9q2aThqcD69THMTqI/edit#heading=h.m96bq8cv9p9v)
**Checked items drafted & ready for implementation**
### [Object Responses](url to section design doc)
**[Qualitative Scales & Parameters](link to section in design doc)**
- Tables (or lists) outlining dynamic parameters (scales & ranges) for each sim concept created
  - [ ] Scale determined for __CONCEPT 1__ : __OBJECT 1__ 
  - [ ] Scale determined for __CONCEPT 2__ : __OBJECT 2__

### [Context Responses](url to section design doc)
**[Complex Context Responses - By Interaction](link to design doc)**
- List out different objects/concepts as needed
  - [ ] Context responses for __OBJECT 1__ 
  - [ ] Context responses for __OBJECT 2__ 

### Simple Context Responses (notes in State Descriptions & PDOM)
**Checked items ready for implementation**
  - [x] Context responses for items in Control Area
  - [x] Common code responses (e.g., Reset All, Mute Sound) verified
  
## [Description Design Testing](url to section design doc)
- [ ] Brief cognitive walkthrough document's the sim's main interaction (highly recommended) 
</details>

# Interactive Description - Implementation
**Checked items verified by designer**
### Static State Descriptions (Screen Summary)
- [ ] H1 for sim title
- [ ] Tab order correct
- [ ] Sim Regions & H2 Headings (Play Area, Control Area, Sim Resources)
- [ ] Static part of screen summary
- [ ] Initial sim-specific interaction hint provided in own paragraph
- [ ] Keyboard Shortcuts interaction hint (PART OF COMMON CODE) 

### Static State Descriptions (Play Area)
- [ ] Sim-specific H3's for sim objects (or none for this sim)
- [ ] Interactions are accessible (i.e., have accessible names, keyboard accessible)
- [ ] Help text for interactive objects

### Static Descriptions (Control Area) 
- [ ] Sim-specific H3s for Control Area (or none for this sim)
- [ ] Interactions are accessible (i.e., names, keyboard accessible)
- [ ] Help text for checkboxes
- [ ] Reset All button

### Sim Resources (Sim Resources)
- [ ] Keyboard Shortcuts dialog completed
    - [ ] Keyboard Shortcuts dialog accessible
	- [ ] Keyboard Shortcuts button added
- [ ] All Audio button (added when sound is added to main sim repo)

### Dynamic State Descriptions
**Add or remove details as needed**
**Dynamic Screen Summary**
- [ ] Phrases work with all parameters
- [ ] Capitalization verified
- [ ] Punctuation verified
- [ ] Edge cases verified

**Play Area Dynamic State Descriptions for Objects**
- [ ] Phrases work with all parameters
- [ ] Capitalization verified
- [ ] Punctuation verified
- [ ] Edge cases verified

### Object Responses (often aria-valuetext)
**Name interactive objects and details as needed**
**Add or remove interactive object details as needed**
**OBJECT Response 1**
- [ ] Qualitative scales verified
- [ ] Quantitative scales verified
- [ ] Increases/decreases verified
- [ ] Steps verified
- [ ] Interaction shotcuts verified (e.g., Home/End keys when appropriate)

### Complex Context Responses (often aria-live regions)
**Name Context Responses and details as needed**

(e.g., GFLB: Responses described force changes specific to changing distance or changing mass; Molarity: Responses described changes to solution concentration specific to Solute Amount changes, Solution Volume changes, and Solute changes)

**Add or remove context details as needed**
**CONTEXT Response 1: OBJECT 1 Increase**
  - [ ] Shared name (between designer and developer) for the context

### Simple Context Responses (Sim options)
**List sim options to verify (e.g., checkboxes in Control Area)**
  - [ ] Checking/unchecking alerts, verified

# Other A11y ToDo's
**Maintain [Accessible Sims page](https://phet.colorado.edu/en/accessibility/prototypes)**
- [ ] Use website admin page (or create issue) to add sim to to A11y Sims page once there is a working prototype
- [ ] Update link to prototype from time to time
  - [ ] At Dev Testing
  - [ ] At RC Testing
  - [ ] At publication

**Accessory Materials**
- [ ] Create issue to update Teacher tips
- [ ] Create issue to create Sound feature videos
- [ ] Create issues to document new or improved design patterns

**Other Features & Items (e.g., Mobile A11y features?)**
- [ ] List items as needed

**Check Credits**
- [ ] Verified A11y team additions: (add names here)
- [ ] Ceate issue with verified a11y team member additions

**Once Evaluation begins**
- [ ] Ensure interviews are recorded to the sim's interview spreadsheet

**During QA or just after publication**
- [ ] Clean and polish up Interactive Description design doc
- [ ] List out main design challenges (if any and if necessary)
- [ ] List out lessons learned from this sim (e.g., found focus issues for iOS)
- [ ] Suggest improvements to THIS issue template

**Housekeeping notes (e.g., significant changes to Checklist (optional)**
